In [1]:
import pandas as pd
import numpy as np

## Preparando dados para análise

In [2]:
police = pd.read_csv('police.csv', sep=',')
weather = pd.read_csv('weather.csv', encoding='utf_8',sep=',')

In [3]:
size = police.shape
print(f'Há {size[0]} linhas e {size[1]} colunas')

Há 91741 linhas e 15 colunas

In [4]:
colunas = police.columns.tolist()
for i in colunas:
    print(f'Há {police[i].isna().sum()} valores vazios na coluna "{i}"')

Há 0 valores vazios na coluna "state"
Há 0 valores vazios na coluna "stop_date"
Há 0 valores vazios na coluna "stop_time"
Há 91741 valores vazios na coluna "county_name"
Há 5205 valores vazios na coluna "driver_gender"
Há 5202 valores vazios na coluna "driver_race"
Há 5202 valores vazios na coluna "violation_raw"
Há 5202 valores vazios na coluna "violation"
Há 0 valores vazios na coluna "search_conducted"
Há 88434 valores vazios na coluna "search_type"
Há 5202 valores vazios na coluna "stop_outcome"
Há 5202 valores vazios na coluna "is_arrested"
Há 5202 valores vazios na coluna "stop_duration"
Há 0 valores vazios na coluna "drugs_related_stop"
Há 0 valores vazios na coluna "district"

In [5]:
police.drop(['county_name', 'state'], axis=1, inplace=True)

In [6]:
police = police.dropna(subset=['driver_gender'], axis=0)

In [7]:
police

,stop_date,stop_time,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,2005-01-04,12:55,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,2005-01-23,23:15,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,2005-02-17,04:15,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,2005-02-20,17:15,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,2005-02-24,01:20,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,21:21,F,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone K2
91737,2015-12-31,21:59,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
91738,2015-12-31,22:04,M,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone X3
91739,2015-12-31,22:09,F,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False,Zone K3
91740,2015-12-31,22:47,M,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False,Zone X4

In [8]:
police['search_conducted'].dtype

dtype('bool')

In [9]:
police['is_arrested'].dtype

dtype('O')

In [10]:
police['district'].dtype

dtype('O')

In [11]:
police.dtypes

stop_date             object
stop_time             object
driver_gender         object
driver_race           object
violation_raw         object
violation             object
search_conducted        bool
search_type           object
stop_outcome          object
is_arrested           object
stop_duration         object
drugs_related_stop      bool
district              object
dtype: object

In [12]:
merge = police.assign(stop_date = police.stop_date + " " + police.stop_time + ":00")

In [13]:
merge

,stop_date,stop_time,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,2005-01-04 12:55:00,12:55,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,2005-01-23 23:15:00,23:15,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,2005-02-17 04:15:00,04:15,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,2005-02-20 17:15:00,17:15,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,2005-02-24 01:20:00,01:20,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31 21:21:00,21:21,F,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone K2
91737,2015-12-31 21:59:00,21:59,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
91738,2015-12-31 22:04:00,22:04,M,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone X3
91739,2015-12-31 22:09:00,22:09,F,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False,Zone K3
91740,2015-12-31 22:47:00,22:47,M,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False,Zone X4

In [14]:
merge.rename(columns = {'stop_date': 'stop_datetime'}, inplace=True)

In [15]:
merge

,stop_datetime,stop_time,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,2005-01-04 12:55:00,12:55,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,2005-01-23 23:15:00,23:15,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,2005-02-17 04:15:00,04:15,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,2005-02-20 17:15:00,17:15,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,2005-02-24 01:20:00,01:20,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31 21:21:00,21:21,F,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone K2
91737,2015-12-31 21:59:00,21:59,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
91738,2015-12-31 22:04:00,22:04,M,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone X3
91739,2015-12-31 22:09:00,22:09,F,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False,Zone K3
91740,2015-12-31 22:47:00,22:47,M,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False,Zone X4

In [16]:
merge.drop(['stop_time'], axis=1, inplace=True)

In [17]:
merge

,stop_datetime,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,2005-01-04 12:55:00,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,2005-01-23 23:15:00,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,2005-02-17 04:15:00,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,2005-02-20 17:15:00,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,2005-02-24 01:20:00,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31 21:21:00,F,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone K2
91737,2015-12-31 21:59:00,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
91738,2015-12-31 22:04:00,M,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone X3
91739,2015-12-31 22:09:00,F,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False,Zone K3
91740,2015-12-31 22:47:00,M,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False,Zone X4

In [18]:
merge['stop_datetime'] = pd.to_datetime(merge['stop_datetime'])

In [19]:
merge.dtypes

stop_datetime         datetime64[ns]
driver_gender                 object
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                   object
stop_duration                 object
drugs_related_stop              bool
district                      object
dtype: object

In [20]:
merge.set_index('stop_datetime', inplace=True)

In [21]:
merge

,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
stop_datetime,,,,,,,,,,,
2005-01-04 12:55:00,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
2005-01-23 23:15:00,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2005-02-17 04:15:00,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
2005-02-20 17:15:00,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
2005-02-24 01:20:00,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
...,...,...,...,...,...,...,...,...,...,...,...
2015-12-31 21:21:00,F,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone K2
2015-12-31 21:59:00,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2015-12-31 22:04:00,M,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone X3
2015-12-31 22:09:00,F,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False,Zone K3
2015-12-31 22:47:00,M,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False,Zone X4

## Análise de gênero sobre as infrações

In [67]:
violations = pd.DataFrame(merge.groupby(['violation']).agg(n_occurrences = ('violation', 'count'))
violations.reset_index(inplace=True)
print(violations.max())
print("\n")
print(violations.min())

TypeError: unhashable type: 'DataFrame'

In [167]:
viol_gender = merge[['violation', 'driver_gender']]
gen = viol_gender['driver_gender'].unique

In [168]:
gp = viol_gender.groupby(['violation', 'driver_gender']).agg(num = ('driver_gender', 'count'))

In [173]:
gp.reset_index(level=[1])

                    driver_gender    num
violation
Equipment                       F   2501
Equipment                       M   8420
Moving violation                F   3286
Moving violation                M  12938
Other                           F    707
Other                           M   3702
Registration/plates             F   1056
Registration/plates             M   2647
Seat belt                       F    578
Seat belt                       M   2278
Speeding                        F  15646
Speeding                        M  32777

In [174]:
#gp.set_index('num')
gp.pivot_table(index='violation',columns='driver_gender',values='num',aggfunc='count')

driver_gender        F  M
violation
Equipment            1  1
Moving violation     1  1
Other                1  1
Registration/plates  1  1
Seat belt            1  1
Speeding             1  1